cron_batch.resource:
  type: config_entity
  label: 'Config for UnpublishNodeQueue'
  mapping:
    period:
      type: integer
      label: 'Period'
    items:
      type: integer
      label: 'Items to create'
    disabled:
      type: boolean
      label: 'Disabled'
    unpublished_label:
      type: string
      label: 'Unpublished label'
