<?php

/**
 * @file
 * Provides a smile entity entity type.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function login_only_theme() {
  return [
    'login_only' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for smile entity templates.
 *
 * Default template: smile-entity.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the smile entity information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_login_only(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}
