<?php

use Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher;
use Drupal\Core\Entity\EntityInterface;
use Drupal\events\Event\NodeEvent;

/**
 * Implements hook_entity_update().
 */
function events_entity_update(EntityInterface $entity) {
  if ($entity->getEntityTypeId() == 'node') {
    /** @var ContainerAwareEventDispatcher $dispatcher */
    $dispatcher = \Drupal::service('event_dispatcher');
    $event = new NodeEvent($entity);
    $dispatcher->dispatch((object)NodeEvent::NODE_SAVED, $event);
  }

}
