<?php

use Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher;
use Drupal\Core\Entity\EntityInterface;
use Drupal\events\Event\NodeEvent;
use Drupal\node\NodeInterface;

/**
 * Implements hook_node_insert().
 * @param EntityInterface $entity
 */
function events_node_insert(EntityInterface $entity) {
  _node_dispatch_event();
}

/**
 * Implements hook_entity_update().
 * @param EntityInterface $entity
 */
function events_entity_update(EntityInterface $entity) {
  _node_dispatch_event();
}

/**
 *
 */
function _node_dispatch_event(NodeInterface $entity){
  if ($entity->getEntityTypeId() == 'node') {
    /** @var ContainerAwareEventDispatcher $dispatcher */
    $dispatcher = \Drupal::service('event_dispatcher');
    $event = new NodeEvent($entity);
    $dispatcher->dispatch($event, NodeEvent::NODE_SAVED);
  }
}
