<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function pets_owners_form_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == 'search_block_form') {
    $form['keys']['#placeholder'] = 'Enter some text to search';
    $form['keys']['#size']        = 26;
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function pets_owners_form_form_search_block_form_alter(
  &$form,
  \Drupal\Core\Form\FormStateInterface $form_state,
  $form_id
) {
  unset( $form['keys']);
}
