<?php

/**
 * @param array $suggestions
 * @param array $variables
 * Implements hook_theme_suggestions_HOOK_alter.
 */
function subtheme_theme_suggestions_node_alter(array &$suggestions, array $variables) {
  if ($node = \Drupal::routeMatch()->getParameter('node')) {
    $type = $node->bundle();
    if ($type == 'news') {
      $value = $node->get('field_template')->getString();
      $suggestions[] = "node__page__$value";
    }
  }
}
