<?php

use Drupal\node\NodeInterface;

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function cron_batch_node_insert(NodeInterface $node) {
  $data = [
    'title' => $node->label(),
    'id' => $node->id(),
  ];
  $queue = \Drupal::queue('db_logger');
  $queue->createQueue();
  $queue->createItem($data);
}



/**
 * Implements hook_cron().
 */
function cron_batch_cron(){
  $conf = \Drupal::configFactory()->get("cron_batch.resource");
  $limit = $conf->get('items');
  $period = time() - $conf->get('period');
  if ($conf->get('disable') == 0) {
    $nids = Drupal::entityQuery('node')
      ->condition('status', TRUE)
      ->condition('changed', $period, '<')
      ->sort('changed', 'DESC')
      ->range(0, $limit)
      ->execute();

    foreach ($nids as $nid) {
      $queue = \Drupal::queue('unpublish_node_queue');
      $queue->createItem($nid);
    }
  }
}

