<?php

/**
 * @file
 * Twig template for render content
 */
function di_block_theme($existing, $type, $theme, $path) {
  return [
    'di_block_theme' => [
      'variables' => [
        'list' => [],
      ],
    ],
  ];
}

function di_block_entity_view_mode_alter(&$view_mode, Drupal\Core\Entity\EntityInterface $entity, $context) {
  // Change the view mode to teaser on full page view for node ID 123.
  if ($entity->getEntityTypeId() == 'node' && $view_mode == 'full') {
    $view_mode = 'teaser';
  }
}
