<?php

/**
 * Implements hook_theme().
 */
function services_block_theme($existing, $type, $theme, $path) {
  return [
    'services_theme' => [
      'variables' => [
        'list' => [],
      ],
    ],
  ];
}

/**
 * @param $view_mode
 * @param \Drupal\Core\Entity\EntityInterface $entity
 * @param $context
 * Implements changing the view mode to teaser on full page view for node ID.
 */
function services_block_entity_view_mode_alter(&$view_mode, \Drupal\Core\Entity\EntityInterface $entity, $context) {
  if ($entity->getEntityTypeId() == 'node' && $view_mode == 'full') {
    $view_mode = 'teaser';
  }
}
